### ISSUE TITLE
Installation fails on Debian 10: undefined symbol: SctpType

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#262]
```
INFO:pathspider:Creating observerbrd ff:ff:ff:ff:ff:ff mss  < pathspid
Traceback (most recent call last):senv$ pspdr measure -i enp0s25 mss  < pathspider/examples/webtest.ndjson  >results.txt
  File "/home/ergadmin/psenv/bin/pspdr", line 11, in <module>
    load_entry_point('pathspider', 'console_scripts', 'pspdr')()
  File "/home/ergadmin/psenv/pathspider/pathspider/cmd/base.py", line 62, in handle_args_wrapper
    handle_args(sys.argv)
  File "/home/ergadmin/psenv/pathspider/pathspider/cmd/base.py", line 57, in handle_args
    args.cmd(args)
  File "/home/ergadmin/psenv/pathspider/pathspider/cmd/measure.py", line 87, in run_measurement
    spider.start()
  File "/home/ergadmin/psenv/pathspider/pathspider/base.py", line 399, in start
    self.observer = self.create_observer()
  File "/home/ergadmin/psenv/pathspider/pathspider/base.py", line 160, in create_observer
    chains=self.chains) # pylint: disable=no-member
  File "/home/ergadmin/psenv/pathspider/pathspider/observer.py", line 88, in __init__
    import plt as libtrace
ImportError: /home/ergadmin/psenv/lib/python3.7/site-packages/plt.cpython-37m-x86_64-linux-gnu.so: undefined symbol: SctpType
```

**Comment by limlynn** [comment]
Same issue here too

`ImportError: /usr/local/lib/python3.6/dist-packages/plt.cpython-36m-x86_64-linux-gnu.so: undefined symbol: SctpType`
