### ISSUE TITLE
observer timer queue corruption

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#27]
With large numbers of workers, the observer's timer queue becomes corrupted:

```
Traceback (most recent call last):
  File "/home/gubser/pathspider/pathspider/base.py", line 329, in exception_wrapper
    target(*args, **kwargs)
  File "/home/gubser/pathspider/pathspider/observer.py", line 267, in run_flow_enqueuer
    f = self._next_flow()
  File "/home/gubser/pathspider/pathspider/observer.py", line 224, in _next_flow   
    if not self._next_packet():
  File "/home/gubser/pathspider/pathspider/observer.py", line 99, in _next_packet  
    self._tick(self._pkt.seconds)
  File "/home/gubser/pathspider/pathspider/observer.py", line 235, in _tick
    heapq.heappop(self._tq).fn()
TypeError: unorderable types: function() < function()
```

This did not happen on a multiday 50-worker run on `pto-de` running d37468a7e9002dfdf3d4fc60925d2363a66f6db2, but did on multiple runs on `pto-nl` and `pto-big-nl` running f1daacb74526f4b6cc9b9f9f3831cb2d44b37845

**Comment by britram** [comment]
Need to see if this is reproducible on the `multiprocessing-observer` branch (see #28)

**Comment by britram** [comment]
Still happens in `multiprocessing-observer` with 200 workers.

**Comment by irl** [comment]
This is not a blocker for 0.9.0.

**Comment by britram** [comment]
@irl, @gubser: definitive word on where this does and does not happen?

**Comment by britram** [comment]
Timer queue has been deleted in `idle_expiring_bintable` branch created to address #68.
